# Generated by Django 4.0.5 on 2022-07-07 18:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidoPaterno', models.CharField(default='', max_length=20, verbose_name='Apellido Paterno')),
                ('apellidoMaterno', models.CharField(default='', max_length=20, verbose_name='Apellido Materno')),
                ('nacimiento', models.DateField(verbose_name='Nacimiento: dd/mm/yyyy')),
                ('correoElectronico', models.EmailField(blank=True, max_length=200, verbose_name='Correo')),
                ('numeroTelefonico', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Numero de telefono')),
                ('vivienda', models.CharField(max_length=100, verbose_name='Lugar Donde Vive')),
                ('nota', models.TextField(blank=True, verbose_name='nota')),
            ],
        ),
    ]
