# Generated by Django 4.0.5 on 2022-07-04 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_numerotelefonico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellidoMaterno',
            field=models.CharField(default='Apellido materno', max_length=20, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidoPaterno',
            field=models.CharField(default='Apellido Paterno', max_length=20, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacimiento',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vivienda',
            field=models.CharField(max_length=100, verbose_name='Lugar Donde Vive'),
        ),
    ]
