# Generated by Django 4.0.5 on 2022-07-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_apellidomaterno_cliente_apellidopaterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nacimiento',
            field=models.DateField(),
        ),
    ]
