# Generated by Django 4.0.5 on 2022-07-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellidoMaterno',
            field=models.CharField(default='', max_length=20, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidoPaterno',
            field=models.CharField(default='', max_length=20, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correoElectronico',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nacimiento',
            field=models.DateField(verbose_name='Nacimiento: dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nota',
            field=models.TextField(blank=True, verbose_name='nota'),
        ),
    ]
